version: '3.7'

services:
  jupyter:
    container_name: jupyter
    image: jxcook/pyinaturalist-notebook
    # Or, to build the image locally:
    # build:
    #   context: .
    #   network: host
    ports:
      - 8888:8888
    volumes:
      # Mount the current directory as the Jupyter workspace
      - .:/home/jovyan/work
      # Or mount your own workspace path
      # - /home/username/workspace:/home/jovyan/work
      # Optional: mount a local Jupyter config dir
      # - ${HOME}/.jupyter:/home/jovyan/.jupyter
      # Optional: mount directory for cached API responses
      # - ${HOME}/.cache:/home/jovyan/.cache
    restart: unless-stopped
    environment:
      # Enable JupyterLab (comment out to use classic notebook)
      JUPYTER_ENABLE_LAB: 'yes'
      # Set any value here to use as a token instead of generating a new one
      # JUPYTER_TOKEN: 'token goes here'
