version: '3.7'

services:
  jupyter:
    container_name: jupyter
    image: jxcook/pyinaturalist-notebook
    # Or, to build the image locally instead of using the version on Docker Hub:
    # build:
    #   context: .
    #   network: host
    ports:
      - 8888:8888
    volumes:
      # Mount the current directory as the Jupyter workspace
      - .:/home/jovyan/work
      # Or mount your own workspace path
      # - /home/username/workspace:/home/jovyan/work
      # Optional: mount a local Jupyter config dir
      # - ${HOME}/.jupyter:/home/jovyan/.jupyter
    restart: unless-stopped
    # environment:
      # Set any value here to use as a token instead of generating one
      # JUPYTER_TOKEN: 'token goes here'
      # Options to manaually set user and group IDs, if needed:
      # CHOWN_HOME: 'yes'
      # CHOWN_HOME_OPTS: -R
      # NB_UID: 1000
      # NB_GID: 1000
    # user: 'root'
