[tool.poetry]
name = "pyinaturalist-notebook"
version = "0.17.2"
description = "A Jupyter notebook image for iNaturalist data exploration & visualization"
authors = ["Jordan Cook"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
altair = ">=4.1"
altair-saver = ">=0.5"
bar_chart_race = ">=0.1"
beautifulsoup4 = ">=4.0"
black = ">=22.3"
dash = ">=1.21"
ipyplot = ">=1.1"
isort = ">=5.10"
jupyterlab-code-formatter = "^1.5.0"
jupyterlab-geojson = "^3.1.2"
pillow = ">=9.1.1"
plotly = ">=5.1"
pyinaturalist-convert = {extras = ["all"], version = ">=0.4"}
vega-datasets = ">=0.9"
websocket-client = "^1.3.1"
xarray = ">=0.18"

# Specific version is optionally set via workflow variable -> Docker build arg
pyinaturalist = {extras = ["all"], version = "*"}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
skip-string-normalization = true
line-length = 100
