name: Publish Docker image

on:
  # Run if triggered by post-release step from pyinaturalist
  repository_dispatch:
    types: [post-release]
  workflow_dispatch:
  # Run if Dockerfile is updated
  push:
    paths:
      - 'Dockerfile'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      - name: Build and publish image
        uses: docker/build-push-action@v2
        with:
          context: .
          pull: true
          push: true
          cache-from: type=registry,ref=jxcook/pyinaturalist-notebook:latest
          cache-to: type=inline
          tags: jxcook/pyinaturalist-notebook:latest
          labels: |
            org.opencontainers.image.source=${{ github.event.repository.html_url }}
            org.opencontainers.image.created=${{ steps.prep.outputs.created }}
            org.opencontainers.image.revision=${{ github.sha }}
