name: Publish Docker image

# Run if triggered by upstream release, if Dockerfile is updated, or if manually triggered
on:
  repository_dispatch:
    types: [post-release]
  push:
    paths:
      - 'Dockerfile'
      - 'poetry.lock'
  workflow_dispatch:
    inputs:
      version:
        description: 'Pyinaturalist version to build'
        required: false
        default: 'latest'

env:
  IMAGE_NAME: jxcook/pyinaturalist-notebook
  PACKAGE_NAME: pyinaturalist

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      # Initial setup + login
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      # Determine package version to install (either specified version or latest)
      - name: Set PyPI package version
        id: pypi
        run: |
          pip install packaging
          IS_LATEST=${{ (github.event.inputs.version || 'latest') == 'latest' }}
          PYPI_VERSION=$(python ${GITHUB_WORKSPACE}/pypi_version.py ${{ env.PACKAGE_NAME }})
          BUILD_VERSION=$(test ${IS_LATEST}=true && echo $PYPI_VERSION || echo ${{ github.event.inputs.version}})
          echo "Latest version: ${PYPI_VERSION} | Build version: ${BUILD_VERSION}"
          echo "::set-output name=version::${BUILD_VERSION}"
          echo "::set-output name=is_latest::${IS_LATEST}"

      # Set Docker tags
      - name: Set Docker tags
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.IMAGE_NAME }}
          flavor: latest=${{ steps.pypi.outputs.is_latest }}
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=sha,prefix=,format=short
            type=semver,pattern={{version}},value=${{ steps.pypi.outputs.version }}
            type=semver,pattern={{major}}.{{minor}},value=${{ steps.pypi.outputs.version }}
            type=semver,pattern={{major}},value=${{ steps.pypi.outputs.version }}

      # Build and publish image
      - name: Build and publish image
        uses: docker/build-push-action@v2
        with:
          context: .
          pull: true
          push: true
          build-args: PACKAGE_VERSION=${{ steps.pypi.outputs.version }}
          cache-from: type=registry,ref=${{ env.IMAGE_NAME }}:latest
          cache-to: type=inline
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

